### ISSUE TITLE
installation package ERROR

### ISSUE THREAD

**Issue by francisangui** [dermatologist/nlp-qrmine#64]
version: Python3.8 
It does not install the package. 

The error I get is the following:

  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.2
    Uninstalling scikit-learn-0.23.2:
      Successfully uninstalled scikit-learn-0.23.2
    Running setup.py install for scikit-learn ... error
    ERROR: Command errored out with exit status 1:

I have tried both on Mac and Windows, the error I get is the same

Thank you for helping!

**Comment by dermatologist** [comment]
I have updated it to a new version. To be consistent, follow the steps below, and please let me know if it works. 

Make sure *python --version* (gives a number >3.7)

In a fresh folder
* python -m venv .venv
* source .venv/bin/activate
(The above steps are for creating a virtual environment. You may be using something else. The above steps are optional)

* pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz#egg=en_core_web_sm
* pip install qrmine==3.6.2
* qrmine --help

**Comment by dermatologist** [comment]
Hi @francisangui 

I have released a new and improved, and stable version of qrmine, called CRISP-T, with LLM support. Please check it out if you are still involved in qualitative research. Qrmine is no longer maintained.

https://github.com/dermatologist/crisp-t

Thanks!


<blockquote><img src="https://repository-images.githubusercontent.com/984123595/5e511d37-3ea9-47ec-88fc-94a84149c9dc" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/dermatologist/crisp-t">GitHub - dermatologist/crisp-t: CRISP-T: Sense-making from Text and Numbers for Qualitative Research!</a></strong></div><div>CRISP-T: Sense-making from Text and Numbers for Qualitative Research! - dermatologist/crisp-t</div></blockquote>
