### ISSUE TITLE
data.read_file doesn’t work

### ISSUE THREAD

**Issue by EdenRochman** [dermatologist/nlp-qrmine#67]
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-7-92ac26365c68> in <module>
      2 data = ReadData()
      3 inp_file = ["Example.txt"]
----> 4 data.read_file(inp_file)

~/XZY/XZD/XZS/XZA/XZW/XZYF/XZK/qrmine/readfiles.py in read_file(self, file_names)
     54             file_name = file_names[0]
     55             with open(file_name, 'r') as f:
---> 56                 read_from_file = f.read()
     57                 self._content = re.sub('<[^<]+?>', '', read_from_file)
     58                 self._documents = re.split('<break>.*?</break>', read_from_file)

~XZD/XZS/XZA/XZW/XZYF/XZK/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 19: invalid continuation byte

**Comment by dermatologist** [comment]
Hi @EdenRochman 
Looks like an encoding issue. The input file is not in utf-8 

If you are on windows try this in a powershell:

```
Get-Content .\Example.txt | Set-Content -Encoding utf8 Example-utf8.txt
```
and use Example-utf8.txt as input.

**Comment by EdenRochman** [comment]
I’m on Mac (and I’m to use qrmine on a Jupiter notebook)

**Comment by dermatologist** [comment]
@EdenRochman  Try this for mac in a command shell. (I assume the encoding is iso-8859-1)

```
iconv -f iso-8859-1 -t utf-8 < Example.txt > Example-utf8.txt

```
and use Example-utf8.txt as input in the notebook.

**Comment by dermatologist** [comment]
Hi @EdenRochman 

I have released an improved and stable version of qrmine, called CRISP-T, with LLM support. Please check it out if you are still involved in qualitative research. Qrmine is no longer maintained.

https://github.com/dermatologist/crisp-t

Thanks!


<blockquote><img src="https://repository-images.githubusercontent.com/984123595/5e511d37-3ea9-47ec-88fc-94a84149c9dc" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/dermatologist/crisp-t">GitHub - dermatologist/crisp-t: CRISP-T: Sense-making from Text and Numbers for Qualitative Research!</a></strong></div><div>CRISP-T: Sense-making from Text and Numbers for Qualitative Research! - dermatologist/crisp-t</div></blockquote>
